### ISSUE TITLE
Сделать поиск по сайту

### ISSUE THREAD

**Issue by mkpankov** [rust-lang-ru/rustycrate.ru#28]

**Comment by mkpankov** [comment]
Варианты: встраиваемый поиск Яндекса, Гугла, [Tapir](http://tapirgo.com/). У последнего интересная модель и API, индексация раз в 15 минут.

**Comment by vessd** [comment]
Думаю встроить https://github.com/christian-fei/Simple-Jekyll-Search. Надо определить что мы хотим от поиска, где он должен располагаться и как выдавать результаты.
По умолчанию он работает так:
![firefox_screenshot_2018-05-08t05-56-44 894z](https://user-images.githubusercontent.com/8783865/39766041-f8ae88ca-52eb-11e8-905c-b5f5ccf6ce05.png)
![firefox_screenshot_2018-05-08t05-57-09 286z](https://user-images.githubusercontent.com/8783865/39766042-f8cc86b8-52eb-11e8-8a13-4f080582c34d.png)
![firefox_screenshot_2018-05-08t05-57-32 898z](https://user-images.githubusercontent.com/8783865/39766043-f8ec8e18-52eb-11e8-9607-36798ee66bb1.png)
![firefox_screenshot_2018-05-08t05-58-29 494z](https://user-images.githubusercontent.com/8783865/39766044-f9095552-52eb-11e8-9c8f-989204055b59.png)

**Comment by vessd** [comment]
![firefox_screenshot_2018-05-09t16-29-36 512z](https://user-images.githubusercontent.com/8783865/39827146-be62f10e-53bf-11e8-8483-ac18df4c273f.png)
![firefox_screenshot_2018-05-09t16-31-23 406z](https://user-images.githubusercontent.com/8783865/39827147-be805f3c-53bf-11e8-8f26-6a54b2924cae.png)
![firefox_screenshot_2018-05-09t16-32-01 888z](https://user-images.githubusercontent.com/8783865/39827148-be9d1744-53bf-11e8-9f58-ba0c4ba1e39a.png)

**Comment by mkpankov** [comment]
Неплохо, но думаю отдельную строку делать нельзя.

Наверное надо реорганизовывать меню, чтобы найти место для строки поиска в верхней строке.

Про реорганизацию была задача.

**Comment by vessd** [comment]
Возможно, но смотреться будет так себе на мой взгляд.Я думал попробовать сделать как на хабре. Кнопка поиска, а по клику выдвигается строчка вместо меню. 14:23, 10 мая 2018 г., Michael Pankov <notifications@github.com>:Между Stackoverflow и Github можно впихнуть, пока меню не переделаем?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  





-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by mkpankov** [comment]
> Возможно, но смотреться будет так себе на мой взгляд.

Я понимаю, это же временный вариант.

> Я думал попробовать сделать как на хабре. Кнопка поиска, а по клику выдвигается строчка вместо меню.

Да, можно.

**Comment by mkpankov** [comment]
Я кое-что понял. В идеале через тот же поиск должно быть можно искать по книгам и форуму.

**Comment by vessd** [comment]
В смысле по книгам? По оглавлению книг или по содержимому?
С книгами на вскидку можно этим поиском, с форумом надо смотреть.

**Comment by mkpankov** [comment]
По содержимому в идеале.

Форум у нас индексируется тем же яндексом.

Мысль в том, что это типа единая точка входа.

Но я не настаиваю, что это всё нужно сделать сразу, можно сначала запустить просто базовый поиск, как сейчас у тебя уже работает.

**Comment by vessd** [comment]
Я не хочу использовать поиск яндекса или гугла потому что они выглядят достаточно убого и напичканы рекламой. Этот поиск придётся допиливать, но не то что бы я знал JS.
Интересно, уместен ли для этой задачи webassembly, если да то возможно получится запилить поиск на Rust...

**Comment by mkpankov** [comment]
Но ведь ты показывал скрины из поиска яндекса?

Я согласен что выглядят они не очень, и нужно будет допиливать фронтенд, но вот писать свой индексатор это точно оверкилл.

**Comment by vessd** [comment]
Нет, это скрины https://github.com/christian-fei/Simple-Jekyll-Search.
Он выдаёт результат поиска по json файлу, который был сформирован с помощью jekyll
```
---
layout: null
---
[
  {% for post in site.posts %}
    {
      "title"    : "{{ post.title | escape }}",
      "category" : "{{ post.categories }}",
      "tags"     : "{{ post.tags | join: ', ' }}",
      "url"      : "{{ site.baseurl }}{{ post.url }}",
      "date"     : "{{ post.date }}"
    } {% unless forloop.last %},{% endunless %}
  {% endfor %}
]
```
А а на скринах просто дефолтный input и результаты в виде списка.
Этот способ вполне подходит для статических сайтов.
Так же можно сделать и для книг, но форум скорее всего идёт мимо.
Сделать поиск по json мы уж как-нибудь сможем...

Других вариантов пока не придумал и нужно ли пока не понятно. Автор поиска там ещё приводит пример генерации json для полнотекстового поиска, но я пока не пробовал.
